    services:
      api:
        image: ghcr.io/ervinhun/todowithextras-api:staging
        env_file:
          - .env
        container_name: todowithextras-api
        ports:
          - "5000:5000"

      client:
        image: ghcr.io/ervinhun/todowithextras-client:staging
        env_file:
          - .env
        container_name: dowa-client
        ports:
          - "80:80"
        depends_on:
          - api

    networks:
      default:
        name: dowa-network